### ISSUE TITLE
Update target pod node selector

### ISSUE THREAD

**Issue by stevefan1999-personal** [openebs/cstor-csi#144]
**Describe the problem/challenge you have**
I want to cluster the node selector to a specific cluster/zone because there is where the majority of the disk are running in.

**Describe the solution you'd like**
Let us update the CStor volume policy, and update the configuration dynamically according to the new settings.

**Environment:**
- OpenEBS version (use `kubectl get po -n openebs --show-labels`): 2.4.0
- Kubernetes version (use `kubectl version`): 1.19.4
- Cloud provider or hardware configuration: Custom built k3s/mixed cloud

**Comment by mittachaitu** [comment]
Hi @stevefan1999-personal, Thanks for reporting the issue it is already supported via Policy(CVP). I also raised a [375](https://github.com/openebs/cstor-operators/pull/375) to add usage of policy to influence scheduling in GitHub docs.
